update create workflow symfony

diff --git a/.github/workflows/symfony.yaml b/.github/workflows/symfony.yaml
--- a/.github/workflows/symfony.yaml
+++ b/.github/workflows/symfony.yaml
@@ -35,7 +35,7 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-php-
       - name: Install Dependencies
-        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
+        run: composer install --no-dev --optimize-autoloader --prefer-dist || (echo "==> Composer installation failed" && cat var/log/*.log || true)
       - name: Create Database
         run: |
           mkdir -p data
